spring:
    datasource:
        url: jdbc:sqlserver://localhost:1433; encrypt=true; trustServerCertificate=true; databaseName=Project
        username: sa 
        password: Database@123
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jpa: 
        show-sql: true
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    mvc:
        pathmatch:
            matching-strategy: ant-path-matcher
server:
    port: 8080
